/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Liveness only. Returns 200 as long as the process is running and has not
         *     been asked to drain. It performs no dependency I/O, so it never turns red
         *     because PostgreSQL or the cache is down — that is `/readyz`.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Drain-aware readiness with a 2 second single-flight cache (ADR-002
         *     § Probes). PostgreSQL unreachable yields 503 `unavailable`. Every other
         *     degraded dependency — cache unreachable, search misconfigured or
         *     unreachable (Q-001), oldest queued job above the configured age
         *     threshold (Q-028) — yields 200 `degraded` with the component named, so a
         *     degraded instance keeps serving reads instead of being pulled out of
         *     rotation.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build identity
         * @description Reports the release tag, commit, build time, Go toolchain, container
         *     image digest, the libvips version and loader list recorded at image
         *     build time (ADR-001), and the maximum migration version embedded in this
         *     binary. The loader list is the only detector for a codec that entered the
         *     image silently, so it is served, not merely logged.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemaz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Migration ledger state
         * @description Always returns 200 (ADR-002 § Probes), including when the ledger is dirty
         *     or behind, because `vizra update` and the deploy scripts read this to
         *     decide whether an image may be rolled out and must be able to distinguish
         *     "behind" from "unreachable". A schema problem is reported in the body,
         *     never as a transport error.
         */
        get: operations["getSchemaz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "status": "ok"
         *     }
         */
        HealthResponse: {
            /**
             * @description `ok` while serving; `draining` after SIGTERM.
             * @enum {string}
             */
            status: "ok" | "draining";
        };
        /**
         * @description `off` means the component is deliberately not configured (for example
         *     `SEARCH_MODE=off`) and is not a fault. A configured-but-unreachable
         *     component is `unavailable` or `degraded`, never `off` — Q-001 forbids a
         *     silent fallback.
         * @enum {string}
         */
        ComponentStatus: "ok" | "degraded" | "unavailable" | "off";
        ReadinessComponent: {
            /**
             * @description Stable component identifier.
             * @enum {string}
             */
            name: "database" | "cache" | "search" | "worker" | "storage";
            status: components["schemas"]["ComponentStatus"];
            /**
             * @description Short human-readable reason. Must never contain credentials, DSNs,
             *     signed URLs, session ids or API keys (ADR-002 § Logging and
             *     redaction).
             */
            detail?: string;
        };
        /**
         * @example {
         *       "status": "degraded",
         *       "components": [
         *         {
         *           "name": "database",
         *           "status": "ok"
         *         },
         *         {
         *           "name": "cache",
         *           "status": "degraded",
         *           "detail": "cache unreachable; using in-process rate limiter"
         *         },
         *         {
         *           "name": "search",
         *           "status": "off"
         *         },
         *         {
         *           "name": "worker",
         *           "status": "ok"
         *         }
         *       ],
         *       "checked_at": "2026-09-20T10:00:00Z"
         *     }
         */
        ReadinessResponse: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            components: components["schemas"]["ReadinessComponent"][];
            /**
             * Format: date-time
             * @description When this result was computed; may be up to 2 s old (single-flight cache).
             */
            checked_at: string;
        };
        LibvipsInfo: {
            /**
             * @description libvips version the image was built against (ADR-001).
             * @example 8.18.6
             */
            version: string;
            /**
             * @description The loader list recorded from `vips -l` at image build time. An
             *     unexpected entry here is how a codec that entered the image silently
             *     is detected.
             */
            loaders: string[];
        };
        VersionResponse: {
            /**
             * @description Release tag, or `dev` for an unreleased build.
             * @example dev
             */
            release: string;
            /** @description Source commit of this binary. */
            commit: string;
            /** Format: date-time */
            built_at: string;
            /** @example go1.27.1 */
            go_version: string;
            /** @description Index digest of the running container image; null outside a container. */
            image_digest?: string | null;
            /** @description Null in binaries built without the libvips image layer (for example `cmd/api` running from source). */
            libvips?: components["schemas"]["LibvipsInfo"] | null;
            /**
             * Format: int64
             * @description Highest migration version embedded in this binary.
             */
            schema_version: number;
            /** @description Selected pinned module versions, for operator diagnosis. */
            modules?: {
                [key: string]: string;
            };
        };
        SchemaResponse: {
            /**
             * Format: int64
             * @description Highest migration version applied to the connected database. 0 on an empty database.
             */
            applied_version: number;
            /**
             * Format: int64
             * @description Highest migration version embedded in this binary.
             */
            embedded_version: number;
            /** @description True when the migration ledger records a failed migration. Reported, never auto-repaired. */
            dirty: boolean;
            /**
             * @description `behind` — the database is older than this binary, run `vizra migrate`.
             *     `ahead` — the database is newer than this binary; `vizra update` refuses
             *     to roll this image out (ADR-002 § Rollback floor).
             *     `unknown` — the ledger could not be read; still 200.
             * @enum {string}
             */
            state: "current" | "behind" | "ahead" | "dirty" | "unknown";
            /** @description Short reason when `state` is `dirty` or `unknown`. Never contains a DSN. */
            detail?: string;
        };
        Error: {
            error: {
                /** @description Stable machine-readable error code. */
                code: string;
                /** @description Human-readable message. Never contains credentials or private metadata. */
                message: string;
                request_id?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description The process is draining and will stop accepting work. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready. `status` is `ok` or `degraded`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Not ready. PostgreSQL is unreachable, or the process is draining. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build identity of the running binary and image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    getSchemaz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Migration ledger state. Always 200. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
        };
    };
}
